snake:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100  

  # Position Controllers ---------------------------------------
  S_00_eff_pos_controller:
    type: effort_controllers/JointPositionController
    joint: link_1_joint
    pid: {p: 3.0, i: 0.0, d: 0.0}

  S_01_eff_pos_controller:
    type: effort_controllers/JointPositionController
    joint: link_2_joint
    pid: {p: 3.0, i: 0.0, d: 0.0}

  S_02_eff_pos_controller:
    type: effort_controllers/JointPositionController
    joint: link_3_joint
    pid: {p: 3.0, i: 0.0, d: 0.0}

  S_03_eff_pos_controller:
    type: effort_controllers/JointPositionController
    joint: link_4_joint
    pid: {p: 3.0, i: 0.0, d: 0.0}

  S_04_eff_pos_controller:
    type: effort_controllers/JointPositionController
    joint: link_5_joint
    pid: {p: 3.0, i: 0.0, d: 0.0}

  S_05_eff_pos_controller:
    type: effort_controllers/JointPositionController
    joint: link_6_joint
    pid: {p: 3.0, i: 0.0, d: 0.0}

#  S_06_eff_pos_controller:
#    type: effort_controllers/JointPositionController
#    joint: link_7_joint
#    pid: {p: 3.0, i: 0.0, d: 0.0}


