snake:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100  

  # Position Controllers ---------------------------------------
  link_01_pos_controller:
    type: effort_controllers/JointPositionController
    joint: link_01
    pid: {p: 3.0, i: 0.0, d: 0.0}

  link_02_pos_controller:
    type: effort_controllers/JointPositionController
    joint: link_02
    pid: {p: 3.0, i: 0.0, d: 0.0}

  link_03_pos_controller:
    type: effort_controllers/JointPositionController
    joint: link_03
    pid: {p: 3.0, i: 0.0, d: 0.0}

  link_04_pos_controller:
    type: effort_controllers/JointPositionController
    joint: link_04
    pid: {p: 3.0, i: 0.0, d: 0.0}

  link_05_pos_controller:
    type: effort_controllers/JointPositionController
    joint: link_05
    pid: {p: 3.0, i: 0.0, d: 0.0}

  link_06_pos_controller:
    type: effort_controllers/JointPositionController
    joint: link_06
    pid: {p: 3.0, i: 0.0, d: 0.0}

  link_07_pos_controller:
    type: effort_controllers/JointPositionController
    joint: link_07
    pid: {p: 3.0, i: 0.0, d: 0.0}

  link_08_pos_controller:
    type: effort_controllers/JointPositionController
    joint: link_08
    pid: {p: 3.0, i: 0.0, d: 0.0}

