---
# list of module names corresponding to each leg.
#
#  front
#  S_00
#    .
#    .
#    .
#  S_15
#  back
#
module_map:
  S_00: link_01
  S_01: link_02
  S_02: link_03
  S_03: link_04
  S_04: link_05
  S_05: link_06
  S_06: link_07
  S_07: link_08
...